# Generated by Django 5.1.7 on 2026-01-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[('livealoe', 'Livealoe'), ('laszlo', 'Laszlo'), ('terra_flor', 'Terra Flor'), ('amo_karite', 'Amo Karitê')], max_length=50)),
                ('descricao_curta', models.TextField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='produtos/')),
            ],
        ),
    ]
